# Generated by Django 5.0.6 on 2026-04-28 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationcriteria',
            options={'ordering': ['-weight'], 'verbose_name_plural': 'Evaluation Criteria'},
        ),
        migrations.AddField(
            model_name='evaluationcriteria',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_criteria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluationcriteria',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluationcriteria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Weight as decimal (e.g., 0.40 for 40%)', max_digits=5),
        ),
    ]
